In [18]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [19]:
df = pd.read_csv("games.csv")
df

,GameID,Steam_AppID,Game_Name,Game_Year,Initial_Price,Rating_Tier,Metacritics,Steam_Total_Reviews,Game_Genres_All
0,1,3059010,Commando Collection,2024,4.99,Overwhelmingly Positive,NaN,1709,Adventure|Action|Casual
1,2,1266840,The Last Stand: Aftermath,2021,24.50,Very Positive,NaN,6848,Adventure|Action
2,3,11050,Dracula: Origin,2008,9.99,Mostly Positive,70.0,387,Adventure|Casual
3,4,456660,Slime & Friends,2016,0.79,Mixed,NaN,71,Casual
4,5,513320,ALICE VR,2016,9.99,Negative,55.0,360,Adventure
...,...,...,...,...,...,...,...,...,...
1495,1496,1357610,Desktop Farm,2020,2.99,Mostly Positive,NaN,684,Strategy|Simulation|Casual
1496,1497,434420,The Chosen RPG,2016,1.99,Mostly Positive,NaN,1239,RPG|Adventure|Action
1497,1498,33460,From Dust,2011,9.99,Mixed,76.0,2992,Simulation|Adventure
1498,1499,2162800,shapez 2: Factory,2026,28.99,Overwhelmingly Positive,80.0,15484,Strategy|Simulation|Casual
1499,1500,1041920,If Found...,2020,11.99,Very Positive,84.0,2375,Casual

In [20]:
df = df.drop(columns=["Metacritics"])
df

,GameID,Steam_AppID,Game_Name,Game_Year,Initial_Price,Rating_Tier,Steam_Total_Reviews,Game_Genres_All
0,1,3059010,Commando Collection,2024,4.99,Overwhelmingly Positive,1709,Adventure|Action|Casual
1,2,1266840,The Last Stand: Aftermath,2021,24.50,Very Positive,6848,Adventure|Action
2,3,11050,Dracula: Origin,2008,9.99,Mostly Positive,387,Adventure|Casual
3,4,456660,Slime & Friends,2016,0.79,Mixed,71,Casual
4,5,513320,ALICE VR,2016,9.99,Negative,360,Adventure
...,...,...,...,...,...,...,...,...
1495,1496,1357610,Desktop Farm,2020,2.99,Mostly Positive,684,Strategy|Simulation|Casual
1496,1497,434420,The Chosen RPG,2016,1.99,Mostly Positive,1239,RPG|Adventure|Action
1497,1498,33460,From Dust,2011,9.99,Mixed,2992,Simulation|Adventure
1498,1499,2162800,shapez 2: Factory,2026,28.99,Overwhelmingly Positive,15484,Strategy|Simulation|Casual
1499,1500,1041920,If Found...,2020,11.99,Very Positive,2375,Casual

In [36]:
df["Popularity"] = pd.cut(
    df["Steam_Total_Reviews"],
    bins=[0, 500, 2000, 10000, float("inf")],
    labels=["Niche", "Moderate", "Popular", "Blockbuster"],
    right=False,
).astype(str)

#df = df.drop(columns=["Steam_Total_Reviews"])
print(df["Popularity"].value_counts())

Popularity
Popular        467
Moderate       432
Niche          303
Blockbuster    298
Name: count, dtype: int64

In [37]:
df.head()

,GameID,Steam_AppID,Game_Name,Game_Year,Initial_Price,Rating_Tier,Steam_Total_Reviews,Game_Genres_All,Popularity
0,1,3059010,Commando Collection,2024,4.99,Overwhelmingly Positive,1709,Adventure|Action|Casual,Moderate
1,2,1266840,The Last Stand: Aftermath,2021,24.50,Very Positive,6848,Adventure|Action,Popular
2,3,11050,Dracula: Origin,2008,9.99,Mostly Positive,387,Adventure|Casual,Niche
3,4,456660,Slime & Friends,2016,0.79,Mixed,71,Casual,Niche
4,5,513320,ALICE VR,2016,9.99,Negative,360,Adventure,Niche

In [38]:
df["Game_Genre"] = df["Game_Genres_All"].str.split("|").str[0]
df.loc[df["Game_Genre"] == "", "Game_Genre"] = "Other"

print(df["Game_Genre"].value_counts())

Game_Genre
RPG                      366
Adventure                346
Strategy                 245
Action                   244
Simulation               166
Casual                    65
Racing                    23
Sports                    13
Massively Multiplayer      5
Name: count, dtype: int64

In [40]:
df["Game_Genre"] = df["Game_Genre"].replace({
    "Racing": "Sports & Racing",
    "Sports": "Sports & Racing",
    "Casual": "Other",
    "Massively Multiplayer": "Other",
})
print(df["Game_Genre"].value_counts())

Game_Genre
RPG                366
Adventure          346
Strategy           245
Action             244
Simulation         166
Other               70
Sports & Racing     36
Name: count, dtype: int64

In [41]:
df.head()

,GameID,Steam_AppID,Game_Name,Game_Year,Initial_Price,Rating_Tier,Steam_Total_Reviews,Game_Genres_All,Popularity,Game_Genre
0,1,3059010,Commando Collection,2024,4.99,Overwhelmingly Positive,1709,Adventure|Action|Casual,Moderate,Adventure
1,2,1266840,The Last Stand: Aftermath,2021,24.50,Very Positive,6848,Adventure|Action,Popular,Adventure
2,3,11050,Dracula: Origin,2008,9.99,Mostly Positive,387,Adventure|Casual,Niche,Adventure
3,4,456660,Slime & Friends,2016,0.79,Mixed,71,Casual,Niche,Other
4,5,513320,ALICE VR,2016,9.99,Negative,360,Adventure,Niche,Adventure

In [42]:
df = df.drop(columns=["Game_Genres_All","Steam_Total_Reviews"])

In [43]:
df.to_csv("cleaned games.csv", index=False)