In [1]:
import pandas as pd
import matplotlib

In [2]:
df_G = pd.read_csv("excel files\games.csv")
df_G.head()

,GameID,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio
0,1,Vampire: The Masquerade – Bloodlines 2,2025,Action,Action Adventure,Hardsuit Labs
1,2,Hollow Knight: Silksong,2025,Platformer,3D Platformer,Team Cherry
2,3,Clair Obscur: Expedition 33,2025,RPG,Action RPG,Sundial Interactive
3,4,Hades 2,2025,Action,Action Adventure,Supergiant Games
4,5,Split Fiction,2025,Action,Action Adventure,Hazelight

In [4]:
df_R = pd.read_csv("excel files\Reviews.csv")
df_R.head()

,MetricID,GameID,Steam_AppID,Steam_Rating_Pct,Steam_Total_Reviews,RAWG_Rating,Added_Count,Ratings_Count,Fetched_At,Metacritics
0,812,164,1966900.0,90.19,29189,3.85,869,100,2026-10-16 18:43:27,NaN
1,813,1252,7510.0,61.61,3227,2.61,2135,165,2026-10-16 18:43:29,54.0
2,814,416,752590.0,93.15,73419,4.14,7181,1547,2026-10-16 18:43:30,81.0
3,815,864,251570.0,86.95,402253,3.36,4332,500,2026-10-16 18:43:32,NaN
4,816,197,1402120.0,76.64,3399,3.63,432,19,2026-10-16 18:43:33,74.0

In [5]:
df_P = pd.read_csv("excel files\steam_prices.csv")
df_P.head()

   PriceID  GameID  Steam_AppID  Initial_Price
0        1    1252         7510          12.79
1        2     164      1966900           4.99
2        3     416       752590          69.99
3        4     864       251570          43.99
4        5     197      1402120          18.49

In [6]:
df = pd.merge(df_G, df_R, on="GameID", how="inner")
df.head()

,GameID,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,MetricID,Steam_AppID,Steam_Rating_Pct,Steam_Total_Reviews,RAWG_Rating,Added_Count,Ratings_Count,Fetched_At,Metacritics
0,1,Vampire: The Masquerade – Bloodlines 2,2025,Action,Action Adventure,Hardsuit Labs,2233,532790.0,55.28,13060,3.83,2487,356,2026-10-16 19:20:16,NaN
1,2,Hollow Knight: Silksong,2025,Platformer,3D Platformer,Team Cherry,1415,1030300.0,89.53,425708,4.38,1685,265,2026-10-16 18:59:42,90.0
2,3,Clair Obscur: Expedition 33,2025,RPG,Action RPG,Sundial Interactive,1034,1903340.0,95.22,280990,4.42,1301,508,2026-10-16 18:49:53,91.0
3,4,Hades 2,2025,Action,Action Adventure,Supergiant Games,1365,1145350.0,95.70,124271,4.36,895,143,2026-10-16 18:58:26,94.0
4,5,Split Fiction,2025,Action,Action Adventure,Hazelight,1949,2001120.0,96.89,128333,4.39,875,257,2026-10-16 19:13:25,NaN

In [7]:
df = pd.merge(df, df_P, on="GameID", how="inner")
df.head()

,GameID,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,MetricID,Steam_AppID_x,Steam_Rating_Pct,Steam_Total_Reviews,RAWG_Rating,Added_Count,Ratings_Count,Fetched_At,Metacritics,PriceID,Steam_AppID_y,Initial_Price
0,1,Vampire: The Masquerade – Bloodlines 2,2025,Action,Action Adventure,Hardsuit Labs,2233,532790.0,55.28,13060,3.83,2487,356,2026-10-16 19:20:16,NaN,1270,532790,59.99
1,2,Hollow Knight: Silksong,2025,Platformer,3D Platformer,Team Cherry,1415,1030300.0,89.53,425708,4.38,1685,265,2026-10-16 18:59:42,90.0,550,1030300,19.50
2,3,Clair Obscur: Expedition 33,2025,RPG,Action RPG,Sundial Interactive,1034,1903340.0,95.22,280990,4.42,1301,508,2026-10-16 18:49:53,91.0,205,1903340,59.99
3,4,Hades 2,2025,Action,Action Adventure,Supergiant Games,1365,1145350.0,95.70,124271,4.36,895,143,2026-10-16 18:58:26,94.0,503,1145350,28.99
4,5,Split Fiction,2025,Action,Action Adventure,Hazelight,1949,2001120.0,96.89,128333,4.39,875,257,2026-10-16 19:13:25,NaN,1025,2001120,49.99

In [8]:
df = df.drop(columns=["GameID","MetricID","PriceID","Steam_AppID_x","Steam_AppID_y","Fetched_At"])
df

,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,Steam_Rating_Pct,Steam_Total_Reviews,RAWG_Rating,Added_Count,Ratings_Count,Metacritics,Initial_Price
0,Vampire: The Masquerade – Bloodlines 2,2025,Action,Action Adventure,Hardsuit Labs,55.28,13060,3.83,2487,356,NaN,59.99
1,Hollow Knight: Silksong,2025,Platformer,3D Platformer,Team Cherry,89.53,425708,4.38,1685,265,90.0,19.50
2,Clair Obscur: Expedition 33,2025,RPG,Action RPG,Sundial Interactive,95.22,280990,4.42,1301,508,91.0,59.99
3,Hades 2,2025,Action,Action Adventure,Supergiant Games,95.70,124271,4.36,895,143,94.0,28.99
4,Split Fiction,2025,Action,Action Adventure,Hazelight,96.89,128333,4.39,875,257,NaN,49.99
...,...,...,...,...,...,...,...,...,...,...,...,...
1342,Full Spectrum Warrior,2004,Action,Action Adventure,Pandemic Studios,73.08,338,3.00,442,25,80.0,6.99
1343,Star Wars: Knights of the Old Republic,2003,Action,Action Adventure,Aspyr Media,91.08,34106,4.35,7039,1483,88.0,9.75
1344,POSTAL 2,2003,Shooter,Tactical Shooter,Running With Scissors,96.94,138892,3.91,6352,1081,59.0,9.75
1345,Max Payne 2: The Fall of Max Payne,2003,Shooter,Tactical Shooter,Remedy Entertainment,94.36,14897,4.42,4945,1639,86.0,14.99
1346,Day of Defeat,2003,Action,Action Adventure,Valve Software,90.19,7387,2.83,4590,279,79.0,4.89

In [9]:
df = df.drop_duplicates(subset=["Game_Name"], keep="first")
print("Duplicate games count remaining:", df.duplicated(subset=["Game_Name"]).sum())

Duplicate games count remaining: 0

In [10]:
df = df.dropna(subset=['Steam_Rating_Pct']).reset_index(drop=True)

In [11]:
df[df["Initial_Price"].isnull()]

,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,Steam_Rating_Pct,Steam_Total_Reviews,RAWG_Rating,Added_Count,Ratings_Count,Metacritics,Initial_Price
176,KartRider: Drift,2023,Sports,Sports Sim,NEXON KOREA,74.01,5145,2.25,480,19,76.0,NaN
194,MultiVersus,2022,Action,Action Adventure,Player First Games,76.10,115948,3.15,3455,186,75.0,NaN
217,Resident Evil Re:Verse,2022,Shooter,Tactical Shooter,Capcom,34.20,4895,1.50,1703,70,NaN,NaN
222,Call of Duty: Modern Warfare 2,2022,Shooter,Tactical Shooter,Raven Software,58.59,783733,3.82,1428,238,NaN,NaN
281,Vampire: The Masquerade: Bloodhunt,2021,Action,Action Adventure,Sharkmob,77.17,59472,2.99,2069,123,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,Doom 3,2004,Shooter,Tactical Shooter,id Software,89.13,8476,3.90,3985,636,87.0,NaN
1311,Unreal Tournament 2004: Editor's Choice Edition,2004,Action,Action Adventure,Epic Games,96.49,4239,4.30,1541,165,93.0,NaN
1313,Neighbours from Hell Compilation,2004,Action,Action Adventure,JoWooD,97.67,3170,3.93,1359,179,69.0,NaN
1319,BloodRayne 2,2004,Shooter,Tactical Shooter,Sony Interactive Entertainment,72.52,444,3.73,871,197,67.0,NaN
1320,OpenTTD,2004,Action,Action Adventure,ZodTTD,94.57,17067,3.67,863,42,NaN,NaN

In [12]:
df["Metacritics"].isnull().sum()

np.int64(272)

In [13]:
import numpy as np

In [14]:
df["Metacritics"] = df["Metacritics"].fillna(df["Steam_Rating_Pct"])

In [15]:
bins = [-1, 19, 39, 69, 79, 94, 100]
labels = [
    "Overwhelmingly Negative",
    "Mostly Negative",
    "Mixed",
    "Mostly Positive",
    "Very Positive",
    "Overwhelmingly Positive",
]

df["steam_rating_text"] = pd.cut(
    df["Steam_Rating_Pct"], bins=bins, labels=labels
)
df = df.drop(columns=["Steam_Rating_Pct"])

In [16]:
df

,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,Steam_Total_Reviews,RAWG_Rating,Added_Count,Ratings_Count,Metacritics,Initial_Price,steam_rating_text
0,Vampire: The Masquerade – Bloodlines 2,2025,Action,Action Adventure,Hardsuit Labs,13060,3.83,2487,356,55.28,59.99,Mixed
1,Hollow Knight: Silksong,2025,Platformer,3D Platformer,Team Cherry,425708,4.38,1685,265,90.00,19.50,Very Positive
2,Clair Obscur: Expedition 33,2025,RPG,Action RPG,Sundial Interactive,280990,4.42,1301,508,91.00,59.99,Overwhelmingly Positive
3,Hades 2,2025,Action,Action Adventure,Supergiant Games,124271,4.36,895,143,94.00,28.99,Overwhelmingly Positive
4,Split Fiction,2025,Action,Action Adventure,Hazelight,128333,4.39,875,257,96.89,49.99,Overwhelmingly Positive
...,...,...,...,...,...,...,...,...,...,...,...,...
1334,Full Spectrum Warrior,2004,Action,Action Adventure,Pandemic Studios,338,3.00,442,25,80.00,6.99,Mostly Positive
1335,Star Wars: Knights of the Old Republic,2003,Action,Action Adventure,Aspyr Media,34106,4.35,7039,1483,88.00,9.75,Very Positive
1336,POSTAL 2,2003,Shooter,Tactical Shooter,Running With Scissors,138892,3.91,6352,1081,59.00,9.75,Overwhelmingly Positive
1337,Max Payne 2: The Fall of Max Payne,2003,Shooter,Tactical Shooter,Remedy Entertainment,14897,4.42,4945,1639,86.00,14.99,Overwhelmingly Positive
1338,Day of Defeat,2003,Action,Action Adventure,Valve Software,7387,2.83,4590,279,79.00,4.89,Very Positive

In [17]:
df[
    df["steam_rating_text"].isin(
        ["Overwhelmingly Negative"]
    )
]

Empty DataFrame
Columns: [Game_Name, Game_Year, Game_Genre, Game_Subgenre, Game_Studio, Steam_Total_Reviews, RAWG_Rating, Added_Count, Ratings_Count, Metacritics, Initial_Price, steam_rating_text]
Index: []

In [18]:
df["RAWG_Rating"].isnull().sum()

np.int64(5)

In [19]:
df[df["RAWG_Rating"].isnull()]

,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,Steam_Total_Reviews,RAWG_Rating,Added_Count,Ratings_Count,Metacritics,Initial_Price,steam_rating_text
354,Streets of Rage 4,2020,Action,Action Adventure,Playdigious,19832,NaN,0,0,84.0,24.99,Very Positive
628,Street Fighter V,2016,Action,Action Adventure,Capcom,44238,NaN,0,0,89.0,19.99,Mixed
633,Stories: The Path of Destinies,2016,Platformer,3D Platformer,Spearhead Games,6607,NaN,0,0,74.0,14.79,Very Positive
1262,Stubbs the Zombie in Rebel Without a Pulse,2005,Shooter,Tactical Shooter,Aspyr Media,2656,NaN,0,0,72.0,19.50,Very Positive
1310,Street Racing Syndicate,2004,Sports,Sports Sim,Eutechnyx,4401,NaN,0,0,84.5,2.99,Very Positive

In [20]:
# Impute using the median RAWG rating of the dataset
rawg_median = df["RAWG_Rating"].median()
df["RAWG_Rating"] = df["RAWG_Rating"].fillna(rawg_median)
df = df.drop(columns=["Added_Count","Ratings_Count"])
df

,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,Steam_Total_Reviews,RAWG_Rating,Metacritics,Initial_Price,steam_rating_text
0,Vampire: The Masquerade – Bloodlines 2,2025,Action,Action Adventure,Hardsuit Labs,13060,3.83,55.28,59.99,Mixed
1,Hollow Knight: Silksong,2025,Platformer,3D Platformer,Team Cherry,425708,4.38,90.00,19.50,Very Positive
2,Clair Obscur: Expedition 33,2025,RPG,Action RPG,Sundial Interactive,280990,4.42,91.00,59.99,Overwhelmingly Positive
3,Hades 2,2025,Action,Action Adventure,Supergiant Games,124271,4.36,94.00,28.99,Overwhelmingly Positive
4,Split Fiction,2025,Action,Action Adventure,Hazelight,128333,4.39,96.89,49.99,Overwhelmingly Positive
...,...,...,...,...,...,...,...,...,...,...
1334,Full Spectrum Warrior,2004,Action,Action Adventure,Pandemic Studios,338,3.00,80.00,6.99,Mostly Positive
1335,Star Wars: Knights of the Old Republic,2003,Action,Action Adventure,Aspyr Media,34106,4.35,88.00,9.75,Very Positive
1336,POSTAL 2,2003,Shooter,Tactical Shooter,Running With Scissors,138892,3.91,59.00,9.75,Overwhelmingly Positive
1337,Max Payne 2: The Fall of Max Payne,2003,Shooter,Tactical Shooter,Remedy Entertainment,14897,4.42,86.00,14.99,Overwhelmingly Positive
1338,Day of Defeat,2003,Action,Action Adventure,Valve Software,7387,2.83,79.00,4.89,Very Positive

In [21]:
log_reviews = np.log1p(df["Steam_Total_Reviews"])

df["Popularity_Index"] = (log_reviews - log_reviews.min()) / (
    log_reviews.max() - log_reviews.min()
)

# 4. Classify into explicit popularity tiers
bins = [-0.01, 0.35, 0.65, 0.85, 1.00]
labels = ["Niche", "Moderate", "Popular", "Blockbuster"]

df["Popularity"] = pd.cut(
    df["Popularity_Index"], bins=bins, labels=labels
)
df = df.drop(columns=["Steam_Total_Reviews","Popularity_Index"])
df

,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,RAWG_Rating,Metacritics,Initial_Price,steam_rating_text,Popularity
0,Vampire: The Masquerade – Bloodlines 2,2025,Action,Action Adventure,Hardsuit Labs,3.83,55.28,59.99,Mixed,Moderate
1,Hollow Knight: Silksong,2025,Platformer,3D Platformer,Team Cherry,4.38,90.00,19.50,Very Positive,Popular
2,Clair Obscur: Expedition 33,2025,RPG,Action RPG,Sundial Interactive,4.42,91.00,59.99,Overwhelmingly Positive,Popular
3,Hades 2,2025,Action,Action Adventure,Supergiant Games,4.36,94.00,28.99,Overwhelmingly Positive,Popular
4,Split Fiction,2025,Action,Action Adventure,Hazelight,4.39,96.89,49.99,Overwhelmingly Positive,Popular
...,...,...,...,...,...,...,...,...,...,...
1334,Full Spectrum Warrior,2004,Action,Action Adventure,Pandemic Studios,3.00,80.00,6.99,Mostly Positive,Niche
1335,Star Wars: Knights of the Old Republic,2003,Action,Action Adventure,Aspyr Media,4.35,88.00,9.75,Very Positive,Moderate
1336,POSTAL 2,2003,Shooter,Tactical Shooter,Running With Scissors,3.91,59.00,9.75,Overwhelmingly Positive,Popular
1337,Max Payne 2: The Fall of Max Payne,2003,Shooter,Tactical Shooter,Remedy Entertainment,4.42,86.00,14.99,Overwhelmingly Positive,Moderate
1338,Day of Defeat,2003,Action,Action Adventure,Valve Software,2.83,79.00,4.89,Very Positive,Moderate

In [22]:
df.to_csv("excel files\cleaned data.csv", index=False)