In [123]:
import pandas as pd
import matplotlib

In [124]:
df_G = pd.read_csv("excel files\games.csv")
df_G.head()

,GameID,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio
0,201,Grand Theft Auto V,2013,Action,Tactical Shooter,Rockstar North
1,202,The Witcher 3: Wild Hunt,2015,Action,Action RPG,CD PROJEKT RED
2,203,Portal 2,2011,Shooter,Tactical Shooter,Valve Software
3,204,Counter-Strike: Global Offensive,2012,Shooter,Tactical Shooter,Valve Software
4,205,Portal,2007,Action,Tactical Shooter,Valve Software

In [125]:
df_R = pd.read_csv("excel files\steam_reviews.csv")
df_R.head()

,MetricID,GameID,Steam_AppID,Steam_Rating_Pct,Steam_Total_Reviews,RAWG_Rating,Added_Count,Ratings_Count,Fetched_At,Metacritics
0,181,699,251570,87.29,273867,3.36,4331,500,2026-10-01 19:53:18,NaN
1,182,405,752590,93.11,63615,4.14,7179,1546,2026-10-01 19:53:24,81.0
2,183,481,278360,92.68,12178,3.15,6168,644,2026-10-01 19:53:29,73.0
3,184,503,1222700,87.33,78379,4.13,5966,1635,2026-10-01 19:53:34,78.0
4,185,585,384190,93.07,22018,3.91,5172,1097,2026-10-01 19:53:40,83.0

In [126]:
df_P = pd.read_csv("excel files\steam_prices.csv")
df_P.head()

,PriceID,GameID,Steam_AppID,Initial_Price,Final_Price,Discount_Pct,Is_Free,Updated_At
0,509,699,251570,43.99,24.19,45,0,2026-10-01 20:28:56
1,510,405,752590,39.99,3.99,90,0,2026-10-01 20:28:56
2,511,481,278360,14.99,2.99,80,0,2026-10-01 20:28:57
3,512,503,1222700,29.99,8.99,70,0,2026-10-01 20:28:57
4,513,585,384190,19.99,4.99,75,0,2026-10-01 20:28:59

In [127]:
df = pd.merge(df_G, df_R, on="GameID", how="inner")
df.head()

,GameID,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,MetricID,Steam_AppID,Steam_Rating_Pct,Steam_Total_Reviews,RAWG_Rating,Added_Count,Ratings_Count,Fetched_At,Metacritics
0,201,Grand Theft Auto V,2013,Action,Tactical Shooter,Rockstar North,370,3240220,83.47,213584,4.47,22739,7445,2026-10-01 20:00:06,NaN
1,202,The Witcher 3: Wild Hunt,2015,Action,Action RPG,CD PROJEKT RED,607,292030,96.50,831426,NaN,0,0,2026-10-01 20:04:29,93.0
2,203,Portal 2,2011,Shooter,Tactical Shooter,Valve Software,496,620,98.72,390753,4.57,20976,6144,2026-10-01 20:02:14,95.0
3,205,Portal,2007,Action,Tactical Shooter,Valve Software,495,620,98.72,390753,4.48,17885,5056,2026-10-01 20:02:14,95.0
4,206,Tomb Raider,2013,Action,Action Stealth,Crystal Dynamics,618,391220,94.22,127540,4.06,17882,4116,2026-10-01 20:04:39,86.0

In [128]:
df = pd.merge(df, df_P, on="GameID", how="inner")
df.head()

,GameID,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,MetricID,Steam_AppID_x,Steam_Rating_Pct,Steam_Total_Reviews,...,Ratings_Count,Fetched_At,Metacritics,PriceID,Steam_AppID_y,Initial_Price,Final_Price,Discount_Pct,Is_Free,Updated_At
0,201,Grand Theft Auto V,2013,Action,Tactical Shooter,Rockstar North,370,3240220,83.47,213584,...,7445,2026-10-01 20:00:06,NaN,698,3240220,29.99,14.99,50,0,2026-10-01 20:31:32
1,202,The Witcher 3: Wild Hunt,2015,Action,Action RPG,CD PROJEKT RED,607,292030,96.50,831426,...,0,2026-10-01 20:04:29,93.0,934,292030,49.99,24.99,50,0,2026-10-01 20:34:40
2,203,Portal 2,2011,Shooter,Tactical Shooter,Valve Software,496,620,98.72,390753,...,6144,2026-10-01 20:02:14,95.0,823,620,9.75,1.95,80,0,2026-10-01 20:33:12
3,205,Portal,2007,Action,Tactical Shooter,Valve Software,495,620,98.72,390753,...,5056,2026-10-01 20:02:14,95.0,822,620,9.75,1.95,80,0,2026-10-01 20:33:12
4,206,Tomb Raider,2013,Action,Action Stealth,Crystal Dynamics,618,391220,94.22,127540,...,4116,2026-10-01 20:04:39,86.0,945,391220,29.99,4.49,85,0,2026-10-01 20:34:50

In [129]:
df = df.drop(columns=["GameID","MetricID","PriceID","Steam_AppID_x","Steam_AppID_y","Fetched_At","Updated_At"])
df

,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,Steam_Rating_Pct,Steam_Total_Reviews,RAWG_Rating,Added_Count,Ratings_Count,Metacritics,Initial_Price,Final_Price,Discount_Pct,Is_Free
0,Grand Theft Auto V,2013,Action,Tactical Shooter,Rockstar North,83.47,213584,4.47,22739,7445,NaN,29.99,14.99,50,0
1,The Witcher 3: Wild Hunt,2015,Action,Action RPG,CD PROJEKT RED,96.50,831426,NaN,0,0,93.0,49.99,24.99,50,0
2,Portal 2,2011,Shooter,Tactical Shooter,Valve Software,98.72,390753,4.57,20976,6144,95.0,9.75,1.95,80,0
3,Portal,2007,Action,Tactical Shooter,Valve Software,98.72,390753,4.48,17885,5056,95.0,9.75,1.95,80,0
4,Tomb Raider,2013,Action,Action Stealth,Crystal Dynamics,94.22,127540,4.06,17882,4116,86.0,29.99,4.49,85,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,7 Days to Die,2013,Shooter,Survival Horror,Telltale Games,87.29,273867,3.36,4331,500,NaN,43.99,24.19,45,0
518,7 Days to Die,2013,Shooter,Survival Horror,Telltale Games,87.29,273867,3.36,4331,500,NaN,43.99,24.19,45,0
519,7 Days to Die,2013,Shooter,Survival Horror,Telltale Games,87.29,273867,3.36,4331,500,NaN,43.99,24.19,45,0
520,7 Days to Die,2013,Shooter,Survival Horror,Telltale Games,87.29,273867,3.36,4331,500,NaN,43.99,24.19,45,0
521,Kerbal Space Program,2015,Action,Action Adventure,Squad,95.77,121011,4.16,4331,412,88.0,36.99,9.24,75,0

In [130]:
df = df.drop_duplicates(subset=["Game_Name"], keep="first")
print("Duplicate games count remaining:", df.duplicated(subset=["Game_Name"]).sum())

Duplicate games count remaining: 0

In [131]:
df = df.dropna(subset=['Steam_Rating_Pct']).reset_index(drop=True)

In [132]:
df[df["Initial_Price"].isnull()]

,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,Steam_Rating_Pct,Steam_Total_Reviews,RAWG_Rating,Added_Count,Ratings_Count,Metacritics,Initial_Price,Final_Price,Discount_Pct,Is_Free
38,Half-Life 2: Deathmatch,2004,Action,Tactical Shooter,Valve Software,90.16,10260,3.29,11258,908,NaN,NaN,NaN,0,0
52,Half-Life Deathmatch: Source,2006,Action,Tactical Shooter,Valve Software,74.51,4367,3.21,10390,727,NaN,NaN,NaN,0,0
91,ARK: Survival Of The Fittest,2016,Action,Tactical Shooter,Instinct Games,72.53,4623,2.60,8921,523,NaN,NaN,NaN,0,0
159,Ori and the Blind Forest,2015,Action,Metroidvania,Moon Studios,93.83,51100,4.37,7502,1540,88.0,NaN,NaN,0,0
163,Viscera Cleanup Detail: Shadow Warrior,2013,Action,Tactical Shooter,Unknown,80.96,2458,2.59,7414,577,NaN,NaN,NaN,0,0
204,Sleeping Dogs: Definitive Edition,2014,Action,Action Adventure,Feral Interactive,94.08,70640,4.15,6754,1192,NaN,NaN,NaN,0,0
226,Sniper Elite V2,2012,Action,Action Stealth,Rebellion,88.14,6275,3.40,6454,853,66.0,NaN,NaN,0,0
237,POSTAL 2,2003,Action,Tactical Shooter,Running With Scissors,96.98,117919,3.91,6351,1080,59.0,NaN,NaN,0,0
238,Forza Horizon 4,2018,Sports,Tactical Shooter,Playground Games,84.09,44,4.37,6344,1656,NaN,NaN,NaN,0,0
268,Half-Life: Source,2004,Action,Tactical Shooter,Valve Software,74.51,4367,3.71,5998,555,NaN,NaN,NaN,0,0
310,F.E.A.R.,2005,Action,Tactical Shooter,Monolith Productions,93.54,14036,4.27,5485,1046,88.0,NaN,NaN,0,0
329,Mark of the Ninja,2012,Action,Action Stealth,Klei Entertainment,96.87,11742,3.99,5310,769,91.0,NaN,NaN,0,0
350,Dying Light,2015,Action,Action Adventure,Techland,95.23,374064,4.14,7021,1113,87.0,NaN,NaN,0,0
385,Yakuza Kiwami,2016,Action,Action Adventure,Ryu ga Gotoku Studio,82.46,1374,4.10,4745,782,NaN,NaN,NaN,0,0
386,Marvel's Guardians of the Galaxy,2021,Action,Action Adventure,Eidos Montreal,75.00,16,4.29,4743,905,NaN,NaN,NaN,55,0

In [133]:
df["Metacritics"].isnull().sum()

np.int64(136)

In [134]:
import numpy as np

In [135]:
df["Metacritics"] = df["Metacritics"].fillna(df["Steam_Rating_Pct"])

In [136]:
bins = [-1, 19, 39, 69, 79, 94, 100]
labels = [
    "Overwhelmingly Negative",
    "Mostly Negative",
    "Mixed",
    "Mostly Positive",
    "Very Positive",
    "Overwhelmingly Positive",
]

df["steam_rating_text"] = pd.cut(
    df["Steam_Rating_Pct"], bins=bins, labels=labels
)
df = df.drop(columns=["Steam_Rating_Pct"])

In [137]:
df

,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,Steam_Total_Reviews,RAWG_Rating,Added_Count,Ratings_Count,Metacritics,Initial_Price,Final_Price,Discount_Pct,Is_Free,steam_rating_text
0,Grand Theft Auto V,2013,Action,Tactical Shooter,Rockstar North,213584,4.47,22739,7445,83.47,29.99,14.99,50,0,Very Positive
1,The Witcher 3: Wild Hunt,2015,Action,Action RPG,CD PROJEKT RED,831426,NaN,0,0,93.00,49.99,24.99,50,0,Overwhelmingly Positive
2,Portal 2,2011,Shooter,Tactical Shooter,Valve Software,390753,4.57,20976,6144,95.00,9.75,1.95,80,0,Overwhelmingly Positive
3,Portal,2007,Action,Tactical Shooter,Valve Software,390753,4.48,17885,5056,95.00,9.75,1.95,80,0,Overwhelmingly Positive
4,Tomb Raider,2013,Action,Action Stealth,Crystal Dynamics,127540,4.06,17882,4116,86.00,29.99,4.49,85,0,Overwhelmingly Positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,Shadowrun: Dragonfall: Director's Cut,2014,Action,Tactical Shooter,Harebrained Schemes,5464,3.81,4374,367,87.00,14.99,3.74,75,0,Very Positive
433,Awesomenauts,2012,Action,Action Adventure,Ronimo Games,17,3.06,4371,415,94.12,3.99,1.39,65,0,Overwhelmingly Positive
434,ARMA: Cold War Assault,2001,Action,Tactical Shooter,Bohemia Interactive,2403,2.87,4363,212,89.64,9.99,4.99,50,0,Very Positive
435,7 Days to Die,2013,Shooter,Survival Horror,Telltale Games,273867,3.36,4331,500,87.29,43.99,24.19,45,0,Very Positive
436,Kerbal Space Program,2015,Action,Action Adventure,Squad,121011,4.16,4331,412,88.00,36.99,9.24,75,0,Overwhelmingly Positive

In [138]:
df[
    df["steam_rating_text"].isin(
        ["Overwhelmingly Negative"]
    )
]

,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,Steam_Total_Reviews,RAWG_Rating,Added_Count,Ratings_Count,Metacritics,Initial_Price,Final_Price,Discount_Pct,Is_Free,steam_rating_text
254,Tom Clancy's The Division,2016,Action,Tactical Shooter,Ubisoft,6,3.7,6143,1351,16.67,49.99,49.99,0,0,Overwhelmingly Negative

In [139]:
df["RAWG_Rating"].isnull().sum()

np.int64(14)

In [140]:
df[df["RAWG_Rating"].isnull()]

,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,Steam_Total_Reviews,RAWG_Rating,Added_Count,Ratings_Count,Metacritics,Initial_Price,Final_Price,Discount_Pct,Is_Free,steam_rating_text
1,The Witcher 3: Wild Hunt,2015,Action,Action RPG,CD PROJEKT RED,831426,NaN,0,0,93.00,49.99,24.99,50,0,Overwhelmingly Positive
17,Cyberpunk 2077,2020,Action,Tactical Shooter,CD PROJEKT RED,885274,NaN,0,0,86.00,59.99,17.99,70,0,Very Positive
29,The Witcher 2: Assassins of Kings Enhanced Edi...,2012,RPG,Action RPG,CD PROJEKT RED,80984,NaN,0,0,88.00,19.99,2.99,85,0,Very Positive
58,Dishonored 2,2016,Action,Tactical Shooter,Bethesda Softworks,43018,NaN,0,0,86.00,29.99,5.99,80,0,Very Positive
109,Mafia 2,2010,Action,Action Adventure,2K Czech,28969,NaN,0,0,74.37,29.99,5.99,80,0,Mostly Positive
129,Cuphead,2017,Action,Action Adventure,Studio MDHR,199260,NaN,0,0,88.00,19.99,13.99,30,0,Overwhelmingly Positive
149,Ori and the Blind Forest: Definitive Edition,2016,Action,Metroidvania,Moon Studios,62801,NaN,0,0,88.00,19.99,4.99,75,0,Overwhelmingly Positive
213,Mafia 3,2016,Action,Action Stealth,Aspyr Media,41691,NaN,0,0,57.64,29.99,5.99,80,0,Mixed
231,The Witness,2016,Action,Tactical Shooter,NVIDIA Lightspeed Studios,17220,NaN,0,0,87.00,36.99,3.69,90,0,Very Positive
328,Mafia 2: Definitive Edition,2020,Action,Action Adventure,Hangar 13,28969,NaN,0,0,74.37,29.99,5.99,80,0,Mostly Positive
371,Crysis 2: Maximum Edition,2011,Action,Tactical Shooter,Crytek,9349,NaN,0,0,86.21,29.99,7.49,75,0,Very Positive
373,Crash Bandicoot N. Sane Trilogy,2017,Action,Action Adventure,Activision,16712,NaN,0,0,92.22,39.99,15.99,60,0,Very Positive
383,Crysis,2007,Action,Tactical Shooter,Electronic Arts,7757,NaN,0,0,88.24,29.99,13.49,55,0,Very Positive
430,Orcs Must Die! 2,2012,Action,Action Adventure,Robot Entertainment,12934,NaN,0,0,83.00,12.49,3.12,75,0,Very Positive

In [141]:
# Impute using the median RAWG rating of the dataset
rawg_median = df["RAWG_Rating"].median()
df["RAWG_Rating"] = df["RAWG_Rating"].fillna(rawg_median)
df = df.drop(columns=["Added_Count","Ratings_Count"])
df

,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,Steam_Total_Reviews,RAWG_Rating,Metacritics,Initial_Price,Final_Price,Discount_Pct,Is_Free,steam_rating_text
0,Grand Theft Auto V,2013,Action,Tactical Shooter,Rockstar North,213584,4.47,83.47,29.99,14.99,50,0,Very Positive
1,The Witcher 3: Wild Hunt,2015,Action,Action RPG,CD PROJEKT RED,831426,3.96,93.00,49.99,24.99,50,0,Overwhelmingly Positive
2,Portal 2,2011,Shooter,Tactical Shooter,Valve Software,390753,4.57,95.00,9.75,1.95,80,0,Overwhelmingly Positive
3,Portal,2007,Action,Tactical Shooter,Valve Software,390753,4.48,95.00,9.75,1.95,80,0,Overwhelmingly Positive
4,Tomb Raider,2013,Action,Action Stealth,Crystal Dynamics,127540,4.06,86.00,29.99,4.49,85,0,Overwhelmingly Positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,Shadowrun: Dragonfall: Director's Cut,2014,Action,Tactical Shooter,Harebrained Schemes,5464,3.81,87.00,14.99,3.74,75,0,Very Positive
433,Awesomenauts,2012,Action,Action Adventure,Ronimo Games,17,3.06,94.12,3.99,1.39,65,0,Overwhelmingly Positive
434,ARMA: Cold War Assault,2001,Action,Tactical Shooter,Bohemia Interactive,2403,2.87,89.64,9.99,4.99,50,0,Very Positive
435,7 Days to Die,2013,Shooter,Survival Horror,Telltale Games,273867,3.36,87.29,43.99,24.19,45,0,Very Positive
436,Kerbal Space Program,2015,Action,Action Adventure,Squad,121011,4.16,88.00,36.99,9.24,75,0,Overwhelmingly Positive

In [142]:
log_reviews = np.log1p(df["Steam_Total_Reviews"])

df["Popularity_Index"] = (log_reviews - log_reviews.min()) / (
    log_reviews.max() - log_reviews.min()
)

# 4. Classify into explicit popularity tiers
bins = [-0.01, 0.35, 0.65, 0.85, 1.00]
labels = ["Niche", "Moderate", "Popular", "Blockbuster"]

df["Popularity"] = pd.cut(
    df["Popularity_Index"], bins=bins, labels=labels
)
df = df.drop(columns=["Steam_Total_Reviews","Popularity_Index"])
df

,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,RAWG_Rating,Metacritics,Initial_Price,Final_Price,Discount_Pct,Is_Free,steam_rating_text,Popularity
0,Grand Theft Auto V,2013,Action,Tactical Shooter,Rockstar North,4.47,83.47,29.99,14.99,50,0,Very Positive,Popular
1,The Witcher 3: Wild Hunt,2015,Action,Action RPG,CD PROJEKT RED,3.96,93.00,49.99,24.99,50,0,Overwhelmingly Positive,Blockbuster
2,Portal 2,2011,Shooter,Tactical Shooter,Valve Software,4.57,95.00,9.75,1.95,80,0,Overwhelmingly Positive,Popular
3,Portal,2007,Action,Tactical Shooter,Valve Software,4.48,95.00,9.75,1.95,80,0,Overwhelmingly Positive,Popular
4,Tomb Raider,2013,Action,Action Stealth,Crystal Dynamics,4.06,86.00,29.99,4.49,85,0,Overwhelmingly Positive,Popular
...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,Shadowrun: Dragonfall: Director's Cut,2014,Action,Tactical Shooter,Harebrained Schemes,3.81,87.00,14.99,3.74,75,0,Very Positive,Moderate
433,Awesomenauts,2012,Action,Action Adventure,Ronimo Games,3.06,94.12,3.99,1.39,65,0,Overwhelmingly Positive,Niche
434,ARMA: Cold War Assault,2001,Action,Tactical Shooter,Bohemia Interactive,2.87,89.64,9.99,4.99,50,0,Very Positive,Moderate
435,7 Days to Die,2013,Shooter,Survival Horror,Telltale Games,3.36,87.29,43.99,24.19,45,0,Very Positive,Popular
436,Kerbal Space Program,2015,Action,Action Adventure,Squad,4.16,88.00,36.99,9.24,75,0,Overwhelmingly Positive,Popular

In [143]:
def categorize_pricing(row):
    if pd.notnull(row["Discount_Pct"]) and row["Discount_Pct"] != 0:
        return "Offre"
    elif row["Is_Free"] == 0:
        return "Free"
    else:
        return "Paid"

df["Pricing"] = df.apply(categorize_pricing, axis=1)
df = df.drop(columns=["Is_Free"])
df

,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,RAWG_Rating,Metacritics,Initial_Price,Final_Price,Discount_Pct,steam_rating_text,Popularity,Pricing
0,Grand Theft Auto V,2013,Action,Tactical Shooter,Rockstar North,4.47,83.47,29.99,14.99,50,Very Positive,Popular,Offre
1,The Witcher 3: Wild Hunt,2015,Action,Action RPG,CD PROJEKT RED,3.96,93.00,49.99,24.99,50,Overwhelmingly Positive,Blockbuster,Offre
2,Portal 2,2011,Shooter,Tactical Shooter,Valve Software,4.57,95.00,9.75,1.95,80,Overwhelmingly Positive,Popular,Offre
3,Portal,2007,Action,Tactical Shooter,Valve Software,4.48,95.00,9.75,1.95,80,Overwhelmingly Positive,Popular,Offre
4,Tomb Raider,2013,Action,Action Stealth,Crystal Dynamics,4.06,86.00,29.99,4.49,85,Overwhelmingly Positive,Popular,Offre
...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,Shadowrun: Dragonfall: Director's Cut,2014,Action,Tactical Shooter,Harebrained Schemes,3.81,87.00,14.99,3.74,75,Very Positive,Moderate,Offre
433,Awesomenauts,2012,Action,Action Adventure,Ronimo Games,3.06,94.12,3.99,1.39,65,Overwhelmingly Positive,Niche,Offre
434,ARMA: Cold War Assault,2001,Action,Tactical Shooter,Bohemia Interactive,2.87,89.64,9.99,4.99,50,Very Positive,Moderate,Offre
435,7 Days to Die,2013,Shooter,Survival Horror,Telltale Games,3.36,87.29,43.99,24.19,45,Very Positive,Popular,Offre
436,Kerbal Space Program,2015,Action,Action Adventure,Squad,4.16,88.00,36.99,9.24,75,Overwhelmingly Positive,Popular,Offre

In [144]:
df.to_csv("excel files\cleaned data.csv", index=False)